"""The corpus index (docs/08-benchmark/CORPUS_INDEX.md): one row per sample, JSON lines."""

from __future__ import annotations

import hashlib
import json
import pathlib
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

Family = Literal["visual", "structural", "semantic-override", "unicode", "metadata", "none"]
InjectionKind = Literal["instruction", "data", "none"]
Split = Literal["train", "test", "unseen_generator"]

FAMILY_OF_TECHNIQUE: dict[str, Family] = {
    "pdf.text.low_contrast": "visual",
    "pdf.text.tiny": "visual",
    "pdf.text.offpage": "visual",
    "pdf.render.mode": "visual",
    "pdf.text.opacity": "visual",
    "pdf.layer.hidden": "structural",
    "pdf.text.covered": "visual",
    "pdf.font.tounicode_mismatch": "semantic-override",
    "pdf.actualtext.override": "semantic-override",
    "pdf.font.decoding_fallback": "semantic-override",
    "pdf.metadata.payload": "metadata",
    "pdf.annotation.hidden": "structural",
    "pdf.active.content": "structural",
    "docx.run.vanish": "structural",
    "docx.run.color": "visual",
    "docx.run.tiny": "visual",
    "docx.part.hidden": "structural",
    "text.unicode.invisible": "unicode",
}
"""Attack families for held-out reporting; a technique the map does not know is 'none'."""


class Sample(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    sample_id: str
    path: str
    """Relative to the corpus root; the file itself lives with the source or is generated."""
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    source: str
    source_version: str
    licence: str
    format: str
    labels: tuple[str, ...] = ()
    family: Family = "none"
    injection_kind: InjectionKind = "none"
    base_document: str
    split: Split = "test"
    caveat: str = ""

    @property
    def positive(self) -> bool:
        return bool(self.labels)


class Corpus(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str
    version: str
    root: str
    synthetic: bool
    samples: tuple[Sample, ...]

    def resolve(self, sample: Sample) -> pathlib.Path:
        return pathlib.Path(self.root) / sample.path


def sha256_file(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_index(corpus: Corpus, target: pathlib.Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    head = {
        "name": corpus.name,
        "version": corpus.version,
        "synthetic": corpus.synthetic,
        "samples": len(corpus.samples),
    }
    lines = [json.dumps(head, sort_keys=True)]
    lines += [json.dumps(s.model_dump(mode="json"), sort_keys=True) for s in corpus.samples]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")


def read_index(target: pathlib.Path, root: pathlib.Path) -> Corpus:
    lines = [line for line in target.read_text(encoding="utf-8").splitlines() if line.strip()]
    head = json.loads(lines[0])
    samples = tuple(Sample.model_validate(json.loads(line)) for line in lines[1:])
    return Corpus(
        name=head["name"],
        version=head["version"],
        root=str(root),
        synthetic=bool(head["synthetic"]),
        samples=samples,
    )


def fixtures_corpus(fixtures: pathlib.Path, *, version: str) -> Corpus:
    """The repository's own fixture pairs as a corpus: synthetic, one positive and one negative
    per technique, never a headline number. Positive and negative share a base document."""
    from paperglass.engine import technique_specs  # noqa: PLC0415  # bench stays light to import

    samples: list[Sample] = []
    for technique_id, spec in sorted(technique_specs().items()):
        folder = fixtures / _folder(spec.formats[0]) / technique_id
        for which in ("positive", "negative"):
            path = next(folder.glob(f"{which}.*"))
            labels = (technique_id,) if which == "positive" else ()
            samples.append(
                Sample(
                    sample_id=f"fixtures-{technique_id}-{which}",
                    path=str(path.relative_to(fixtures.parent.parent)),
                    sha256=sha256_file(path),
                    source="paperglass_fixtures",
                    source_version=version,
                    licence="Apache-2.0",
                    format=path.suffix.lstrip("."),
                    labels=labels,
                    family=FAMILY_OF_TECHNIQUE.get(technique_id, "none") if labels else "none",
                    injection_kind=_kind(spec.severity_class.value) if labels else "none",
                    base_document=f"fixtures-{technique_id}",
                    split="test",
                    caveat="synthetic, generated by scripts/make_fixtures.py",
                )
            )
    return Corpus(
        name="fixtures",
        version=version,
        root=str(fixtures.parent.parent),
        synthetic=True,
        samples=tuple(samples),
    )


def _folder(fmt: str) -> str:
    return {"pdf": "pdf", "docx": "docx", "any": "text"}.get(fmt, fmt)


def _kind(severity_class: str) -> InjectionKind:
    if severity_class == "instruction":
        return "instruction"
    if severity_class == "data":
        return "data"
    return "none"
