"""Render BENCHMARK.md tables from results/ (docs/08-benchmark/LEADERBOARD.md)."""

from __future__ import annotations

import pathlib

from paperglass.bench.run import Results, load_results

START = "<!-- bench:start -->"
END = "<!-- bench:end -->"


def _pct(value: float | None) -> str:
    return "n/a" if value is None else f"{value * 100:.1f}%"


def _ms(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.0f} ms"


def render(results: list[Results]) -> str:
    """One table per corpus; synthetic corpora say so in their heading."""
    by_corpus: dict[str, list[Results]] = {}
    for r in results:
        by_corpus.setdefault(f"{r.corpus} {r.corpus_version}", []).append(r)
    out: list[str] = [START, ""]
    for key, rows in sorted(by_corpus.items()):
        synthetic = rows[0].synthetic
        heading = f"### Corpus {key}" + (
            " (synthetic; never a headline number)" if synthetic else ""
        )
        out += [
            heading,
            "",
            "| Detector | Version | Precision | Recall (verdict) | F1 | Detection recall "
            "| Instruction recall | Data recall "
            "| FP rate (verdict-driving) | FP rate (informational) "
            "| Benign-hidden called malicious | p50 | p95 | Hardware | Date | Command |",
            "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|",
        ]
        for r in sorted(rows, key=lambda x: (x.detector, x.detector_version)):
            m = r.metrics
            out.append(
                f"| {r.detector} | {r.detector_version} | {_pct(m.precision)} | {_pct(m.recall)} | "
                f"{_pct(m.f1)} | {_pct(m.detection_recall)} | {_pct(m.recall_instruction)} | "
                f"{_pct(m.recall_data)} | "
                f"{_pct(m.false_positive_rate_verdict_driving)} | "
                f"{_pct(m.false_positive_rate_informational)} | "
                f"{m.benign_hidden_called_malicious} | "
                f"{_ms(m.latency_p50_ms)} | {_ms(m.latency_p95_ms)} | {r.hardware} | {r.date} | "
                f"`{r.command}` |"
            )
        out.append("")
        for r in sorted(rows, key=lambda x: (x.detector, x.detector_version)):
            out += [
                f"Recall per technique, {r.detector} {r.detector_version}:",
                "",
                "| Technique | Recall |",
                "|---|---|",
            ]
            out += [f"| `{t}` | {_pct(v)} |" for t, v in r.metrics.recall_per_technique.items()]
            out.append("")
            out += ["| Family | Recall |", "|---|---|"]
            out += [f"| {f} | {_pct(v)} |" for f, v in r.metrics.recall_per_family.items()]
            out.append("")
    out.append(END)
    return "\n".join(out) + "\n"


def collect(results_root: pathlib.Path) -> list[Results]:
    return [load_results(p) for p in sorted(results_root.glob("*/*/*.json"))]


def splice(document: str, table: str) -> str:
    """Replace the generated block in BENCHMARK.md, or append it."""
    if START in document and END in document:
        head = document[: document.index(START)]
        tail = document[document.index(END) + len(END) :]
        return head + table.rstrip("\n") + tail
    return (
        document.rstrip("\n")
        + "\n\n## Results (generated by `paperglass bench report`)\n\n"
        + table
    )
