"""Shared schema models (Finding, Report, CleanResult, Receipt). Importable by every package."""

from paperglass.models.document import DocumentText, PageText, TextRun
from paperglass.models.docx import DocxPart, DocxRun, DocxStructure
from paperglass.models.fingerprint import ExtractorVerdict, Fingerprint, FingerprintRow
from paperglass.models.raster import InkResult, OcrResult, PageRaster
from paperglass.models.schema import (
    PARSE_FAILURE_TECHNIQUE,
    SCHEMA_VERSION,
    SEVERITY_ORDER,
    BBox,
    CleanResult,
    Finding,
    FindingStatus,
    PageView,
    ParseFailure,
    Receipt,
    RenderCrop,
    Report,
    Run,
    RunStatus,
    RunView,
    Severity,
    SeverityClass,
    Tier,
    Verdict,
    json_schema,
    severity_counts_of,
    sha256_of,
    verdict_of,
)
from paperglass.models.structure import (
    DocumentStructure,
    PageStructure,
    PdfAnnotation,
    PdfColour,
    PdfFontInfo,
    PdfMetadata,
    PdfTextObject,
)

__all__ = [
    "PARSE_FAILURE_TECHNIQUE",
    "SCHEMA_VERSION",
    "SEVERITY_ORDER",
    "BBox",
    "CleanResult",
    "DocumentStructure",
    "DocumentText",
    "DocxPart",
    "DocxRun",
    "DocxStructure",
    "ExtractorVerdict",
    "Finding",
    "FindingStatus",
    "Fingerprint",
    "FingerprintRow",
    "InkResult",
    "OcrResult",
    "PageRaster",
    "PageStructure",
    "PageText",
    "PageView",
    "ParseFailure",
    "PdfAnnotation",
    "PdfColour",
    "PdfFontInfo",
    "PdfMetadata",
    "PdfTextObject",
    "Receipt",
    "RenderCrop",
    "Report",
    "Run",
    "RunStatus",
    "RunView",
    "Severity",
    "SeverityClass",
    "TextRun",
    "Tier",
    "Verdict",
    "json_schema",
    "severity_counts_of",
    "sha256_of",
    "verdict_of",
]
